### PR TITLE
Portfolio Accessibility Pair Programming

### PR DESCRIPTION
**Pull request by sulaimanahmadi**
**Check following things by Agneta Pupienyte, Michael Darkah**

- Page tittle
- Image alt
- Text heading
- Color contrast
- Interaction
- Multi Media

etc....

### CODE REVIEW

**Review by joel-kalema — COMMENTED** [review]
Hi @sulaimanahmadi 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request  🛑 

pirates-of-the-caribbean-johnny-depp


- [ ] You have submitted a project that has linters that does not pass, make sure you solve them and the ask again for a review


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @joel-kalema in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by agneta1991** [comment]
@joel-kalema hello, we have submitted this review as a pair-programming task. we have spoken to a senior developer Ahmet Bozacı regarding a hint showing an issue but in vs code, there are no error, warnings or hints to fix. the senior developer said that there must be an issue with GitHub itself, and it did happen with his student on previous week, the issue is, that linter error asks to change hint files we have installed, but as instructions said we must not change anything within those files. Can you please advise us on how to complete this task without changing the original hint files?

**Comment by joel-kalema** [comment]
- [ ] Hello @sulaimanahmadi @agneta1991 @Mike47ip, I can get the problem you have 😃 , Kindly submit again the pull request, so that we can review your project. 💪. 

Cheers and Happy coding!👏👏👏

**Review by bobb-Rob — APPROVED** [review]
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @sulaimanahmadi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
